version: '3.8'

services:
  # Laravel Application (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: target_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
    #manually go to container and add install composer

  # Nginx Web Server
  webserver:
    image: nginx:alpine
    container_name: target_nginx
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: target_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test1
    ports:
      - "3307:3306"
    volumes:
      - target_db_data:/var/lib/mysql

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: target_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8091:80"
    depends_on:
      - db

volumes:
  target_db_data:
